version: "3.8"

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /data/mongo:/data/db
    ports:
      - 27017:27017
    
  redis:
    image: redis:6.2.13-alpine3.18
    ports:
      - 6379:6379
    volumes:
      - /data/redis:/data